### ISSUE TITLE
Code simplification

### ISSUE THREAD

**Issue by mlyahovi** [ANDREW-LVIV/phplab-tasks#1]
We can use the following construction as well
`return (bool) date('L', mktime(0, 0, 0, 1, 1, $year));`
https://github.com/ANDREW-LVIV/phplab-tasks/blob/a2be73ea41485f74c1358c29e1ebd7442a6a509a/src/01-basics.php#L44

**Comment by ANDREW-LVIV** [comment]
Thanks for the advice.
BTW, do I have to simplify my code, or just take it as a recommendation for the future?

**Comment by mlyahovi** [comment]
> Thanks for the advice.
> BTW, do I have to simplify my code, or just take it as a recommendation for the future?

Just the recommendation for the future :)

**Comment by ANDREW-LVIV** [comment]
Okay! Thanks. I'm closing issue.
