### ISSUE TITLE
Simpler return

### ISSUE THREAD

**Issue by songofthewings** [ANDREW-LVIV/phplab-tasks#2]
Here you can just cast $leap to bool or return `($leap == '1')`

https://github.com/ANDREW-LVIV/phplab-tasks/blob/c0c24aaa081bfeda51e3ac9e05960ca390f96572/src/01-basics.php#L45

**Comment by ANDREW-LVIV** [comment]
A few days ago I received almost the same advice https://github.com/ANDREW-LVIV/phplab-tasks/issues/1#issue-654270824

Thank you for your advice too!
The code has been simplified.
