### ISSUE TITLE
Word matches

### ISSUE THREAD

**Issue by songofthewings** [ANDREW-LVIV/phplab-tasks#3]
There is possibility to do this without explode+foreach - you can make word matches.
https://github.com/ANDREW-LVIV/phplab-tasks/blob/c0c24aaa081bfeda51e3ac9e05960ca390f96572/src/02-strings.php#L26

**Comment by ANDREW-LVIV** [comment]
Could you please give me a hint?

I can use **preg_split("/[\s,]+/", $input)** instead of explode, but it doesn't make any sense to do so.
Also, input may not contain some **english text**, thus it is not possible to use **strrev**.  

I'm confused, how can I rewrite my code by not using **explode** and even **foreach**.
Perhaps I can try preg_replace_callback or not

**Comment by ANDREW-LVIV** [comment]
```
function mirrorMultibyteString(string $input)
{
    preg_match_all('/./us', $input, $array);
    $array2 = join('', array_reverse($array[0]));

    $array3 = preg_split('/[\s,]+/', $array2);
    $array4 = join(' ', array_reverse($array3));

    return $array4;
}
```

**Comment by ANDREW-LVIV** [comment]
```
function mirrorMultibyteString(string $input)
{
    preg_match_all('/./us', $input, $array);
    $array2 = implode('', array_reverse($array[0]));
    $array3 = preg_split('/[\s,]+/', $array2);
    return implode(' ', array_reverse($array3));
}
```

**Comment by ANDREW-LVIV** [comment]
function mirrorMultibyteString(string $input)
{
    preg_match_all('/./us', $input, $array);
    $array2 = implode('', array_reverse($array[0]));
    $array3 = preg_split('/[\s,]+/', $array2);

    return implode(' ', array_reverse($array3));
}

**Comment by ANDREW-LVIV** [comment]
```
function mirrorMultibyteString(string $input) {
    preg_match_all('/./us', $input, $array);
    $array2 = implode('', array_reverse($array[0]));
    $array3 = preg_split('/[\s,]+/', $array2);

    return implode(' ', array_reverse($array3));
}
```

**Comment by ANDREW-LVIV** [comment]
function mirrorMultibyteString(string $input)
{
    preg_match_all('/./us', $input, $array);
    $array2 = implode('', array_reverse($array[0]));
    $array3 = preg_split('/[\s,]+/', $array2);

    return implode(' ', array_reverse($array3));
}

**Comment by ANDREW-LVIV** [comment]
```
function mirrorMultibyteString(string $input)
{
    preg_match_all('/./us', $input, $array);
    $array2 = implode('', array_reverse($array[0]));
    $array3 = preg_split('/[\s,]+/', $array2);

    return implode(' ', array_reverse($array3));
}
```

**Comment by songofthewings** [comment]
> ```
> function mirrorMultibyteString(string $input)
> {
>     preg_match_all('/./us', $input, $array);
>     $array2 = implode('', array_reverse($array[0]));
>     $array3 = preg_split('/[\s,]+/', $array2);
> 
>     return implode(' ', array_reverse($array3));
> }
> ```

This is interesting, you can leave this variant but simpler to use explode instead of preg_split.
I would use array_map, in that case there is no need to reverse twice.

**Comment by ANDREW-LVIV** [comment]
I'm really confused in your task to rewrite by not using **explode**.

Implementation by using **array_map** instead of **foreach**:
```
function mirrorMultibyteString(string $input) {
	$words = array_map(function ($value) {
		preg_match_all('/./us', $value, $letters);
		return implode('', array_reverse($letters[0]));
	}, explode(' ', $input));

	return implode(' ', $words);
}
```

But honestly, this code looks more clear and not so messy in terms of reading:
```
function mirrorMultibyteString(string $input)
{
    preg_match_all('/./us', $input, $array);
    $array2 = implode('', array_reverse($array[0]));
    $array3 = explode(' ', $array2);
    
    return implode(' ', array_reverse($array3));
}
```

By the way, what's the point not to use **foreach** construct but **array_map**? 
Or is it just a matter of learning how to use different options?

It would be nice to see your implementation of this task at the end in order to learn another way.

**Comment by apopova-cartera** [comment]
You can use explode. Final results are good, just commit one to your code.
In this particular case it doesn't matter much. The purpose is to practice different approach which will be useful.

**Comment by songofthewings** [comment]
You can use explode. Final results are good, just commit one to your code.
In this particular case it doesn't matter much. The purpose is to practice different approach which will be useful.
