### ISSUE TITLE
What if argument contains not only lowercase letters

### ISSUE THREAD

**Issue by songofthewings** [ANDREW-LVIV/phplab-tasks#5]
If $noun contains not only lowercase letters, this will not work as required.

https://github.com/ANDREW-LVIV/phplab-tasks/blob/b09e515aaa2cd922cc091d72874fe3d8a4a3a13d/src/02-strings.php#L49

**Comment by ANDREW-LVIV** [comment]
what about `$noun = strtolower($noun); ` before "if" condition?
it converts all letters into lowercase.
I tested this code with Uppercase letters as well and it works.

Please give me an example.

**Comment by songofthewings** [comment]
Please disregard this.
