### ISSUE TITLE
Doesn't work as expected

### ISSUE THREAD

**Issue by mlyahovi** [ANDREW-LVIV/phplab-tasks#6]
https://github.com/ANDREW-LVIV/phplab-tasks/blob/f75f3c4bb42d33783c381f885c5e4b87d0f86cfc/src/03-arrays.php#L32

for example array [100,1,0] return 100. But the lowest unique value is 0

**Comment by ANDREW-LVIV** [comment]
Yes, you are right!
I fixed it by adding `sort($input);`

**Comment by mlyahovi** [comment]
Still not working. For example array [0, -1] return "0". Should be "-1"

**Comment by ANDREW-LVIV** [comment]
Why not?

```
function getUniqueValue(array $input) {
    if (empty($input)) {
        return 0;
    }
    sort($input);
    foreach (array_count_values($input) as $key => $value) {
        if ($value == 1) {
            $result = $key;
            break;
        } else {
            $result = 0;
        }
    }
    return $result;
}
print_r(getUniqueValue([0, -1, 10, 2, 5, 38, 2]));
```

`// Output: -1`

**Comment by mlyahovi** [comment]
Fixed.
