### ISSUE TITLE
safe_var

### ISSUE THREAD

**Issue by songofthewings** [ANDREW-LVIV/phplab-tasks#9]
https://github.com/ANDREW-LVIV/phplab-tasks/blob/3db2d4dff2e00c806519fb16eec10938a1e9c458/src/web/functions.php#L32
stripslashes() had been used in such cases when magic_quotes_gpc is on. But it became deprecated and deleted since php 5.4.0. So please remove it.

**Comment by ANDREW-LVIV** [comment]
but stripslashes() is also available in php ver 7.
ok. in a case it is needed to convert  "Is your name O\'reilly?" into "Is your name O'reilly?" which build functions to use?
